// phrases.yaml → phrases.json. Kana are generated by khmer-kana and never hand-edited (design.md §4.2, §4.3).
import { KhmerKanaError, parseIpa, renderFull, renderLite, toIpa, type Utterance } from "khmer-kana";
import type { PhraseInput, SceneInput } from "./schema";

export type Profile = "prod" | "preview";
/** A scene needs at least this many published phrases to be shown in prod (design.md §4.3). */
export const MIN_PHRASES_PER_SCENE = 4;

export interface Variant {
  speaker: "any" | "male" | "female";
  register: "polite" | "casual";
  khmer: string;
  ipa: string;
  syllables: Utterance;
  kanaFull: string;
  kanaLite: string;
  audio: string;
}
export interface Phrase extends Omit<PhraseInput, "variants" | "words"> {
  variants: Variant[];
  words: { khmer: string; ipa: string; ja: string }[];
  /** true when any review item is still false (preview shows an "未確認" badge). */
  unreviewed: boolean;
}
export interface Scene extends SceneInput { phraseIds: string[] }
export interface Bundle { schema: 1; profile: Profile; scenes: Scene[]; phrases: Phrase[] }
export interface BuildResult { bundle: Bundle; errors: string[]; warnings: string[] }

export interface BuildOptions {
  profile: Profile;
  /** Returns whether an audio file exists. Checked only in prod. */
  audioExists?: (file: string) => boolean;
}

function convertIpa(where: string, ipa: string, errors: string[]): { syllables: Utterance; ipa: string } | undefined {
  try {
    const syllables = parseIpa(ipa);
    return { syllables, ipa: toIpa(syllables) };
  } catch (e) {
    const msg = e instanceof KhmerKanaError ? `${e.code}: ${e.message}` : String(e);
    errors.push(`${where}: IPA "${ipa}" を解析できません (${msg})`);
    return undefined;
  }
}

export function buildBundle(phrases: PhraseInput[], scenes: SceneInput[], opts: BuildOptions): BuildResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const sceneIds = new Set<string>();
  for (const s of scenes) {
    if (sceneIds.has(s.id)) errors.push(`scene ${s.id}: id が重複しています`);
    sceneIds.add(s.id);
  }

  const seen = new Set<string>();
  const built: Phrase[] = [];
  for (const p of phrases) {
    if (seen.has(p.id)) errors.push(`phrase ${p.id}: id が重複しています`);
    seen.add(p.id);
    if (!sceneIds.has(p.scene)) errors.push(`phrase ${p.id}: 未定義のシーン "${p.scene}"`);

    const variants: Variant[] = [];
    const speakers = new Set<string>();
    for (const v of p.variants) {
      const key = `${v.speaker}/${v.register}`;
      if (speakers.has(key)) errors.push(`phrase ${p.id}: variants の ${key} が重複しています`);
      speakers.add(key);
      const r = convertIpa(`phrase ${p.id}`, v.ipa, errors);
      if (!r) continue;
      variants.push({
        ...v,
        ipa: r.ipa,
        syllables: r.syllables,
        kanaFull: renderFull(r.syllables).text,
        kanaLite: renderLite(r.syllables).text,
      });
    }
    if (speakers.has("any/polite") && speakers.size > 1) {
      errors.push(`phrase ${p.id}: speaker any と male/female を polite で併用できません`);
    }
    const words = p.words.map((w) => {
      const r = convertIpa(`phrase ${p.id} の単語 ${w.khmer}`, w.ipa, errors);
      return { ...w, ipa: r?.ipa ?? w.ipa };
    });
    if (words.length === 0) warnings.push(`phrase ${p.id}: words が空です(単語タップができません)`);

    built.push({ ...p, variants, words, unreviewed: !(p.review.ipa && p.review.audio && p.review.usage) });
  }

  let published = built;
  if (opts.profile === "prod") {
    published = built.filter((p) => !p.unreviewed && p.audioSource === "native");
    const exists = opts.audioExists;
    if (exists) {
      for (const p of published) {
        for (const v of p.variants) {
          if (!exists(v.audio)) errors.push(`phrase ${p.id}: 音声ファイル ${v.audio} がありません`);
        }
      }
    }
  }

  const outScenes: Scene[] = [];
  for (const s of [...scenes].sort((a, b) => a.order - b.order)) {
    const ids = published.filter((p) => p.scene === s.id).map((p) => p.id);
    if (opts.profile === "prod" && ids.length < MIN_PHRASES_PER_SCENE) {
      warnings.push(`scene ${s.id}: 公開フレーズが ${ids.length} 件(${MIN_PHRASES_PER_SCENE} 件未満)のため非公開にします`);
      continue;
    }
    outScenes.push({ ...s, phraseIds: ids });
  }
  const visible = new Set(outScenes.flatMap((s) => s.phraseIds));
  const outPhrases = published.filter((p) => visible.has(p.id));

  return { bundle: { schema: 1, profile: opts.profile, scenes: outScenes, phrases: outPhrases }, errors, warnings };
}
