import type { Bundle } from "../../../packages/content/src/build";
import bundle from "../../../packages/content/dist/ja-km/phrases.json";

// dist/ja-km/phrases.json is generated by `pnpm gen` (content build --course ja-km)。コース対応は ADR-0020 の段階2。 The shape is checked here once.
export const data = bundle as unknown as Bundle;
export type { Phrase, Scene, Variant } from "../../../packages/content/src/build";
