import type { Bundle } from "../../../packages/content/src/build";
import bundle from "../../../packages/content/dist/phrases.json";

// dist/phrases.json is generated by `pnpm gen` (content build). The shape is checked here once.
export const data = bundle as unknown as Bundle;
export type { Phrase, Scene, Variant } from "../../../packages/content/src/build";
